### ISSUE TITLE
Getting internal server errors from howopenisit.org

### ISSUE THREAD

**Issue by egh** [CottageLabs/OpenArticleGauge#117]
I am getting internal server errors again from howopenisit.org. Thanks!

**Comment by emanuil-tolev** [comment]
Sorry @egh - actually I logged into the server to fix the problem, but was on trains and my subsequent comment to the effect of "does it work now" never made it to Github!

The service seems to be working (and should have been working over the holidays too). E.g. http://howopenisit.org/lookup/doi:10.1371/journal.pmed.1001745.json .

It should be a lot more stable now, due to various resource problems being resolved. There's more to do of course.

**Comment by egh** [comment]
Thanks!
